import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { ShieldAlert, CheckCircle, ExternalLink, Filter, CheckCheck } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import { getAlerts, resolveAlert, resolveAllAlerts } from '../utils/api';

export default function Alerts() {
  const [alertsData, setAlertsData] = useState({ alerts: [], total_active: 0, critical_count: 0, high_count: 0, medium_count: 0, resolved_count: 0 });
  const [severityFilter, setSeverityFilter] = useState('All');
  const [loading, setLoading] = useState(true);

  async function loadAlerts() {
    try {
      setLoading(true);
      const res = await getAlerts({
        severity: severityFilter,
        limit: 100
      });
      setAlertsData(res);
    } catch (err) {
      console.error('Failed to load alerts:', err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadAlerts();
  }, [severityFilter]);

  const handleResolveOne = async (id) => {
    try {
      await resolveAlert(id);
      loadAlerts();
    } catch (err) {
      console.error(err);
    }
  };

  const handleResolveAll = async () => {
    try {
      await resolveAllAlerts();
      loadAlerts();
    } catch (err) {
      console.error(err);
    }
  };

  const donutData = [
    { name: 'Critical', value: alertsData.critical_count || 10, color: '#C25E3E' },
    { name: 'High', value: alertsData.high_count || 30, color: '#D97706' },
    { name: 'Medium', value: alertsData.medium_count || 50, color: '#2C3E50' },
  ];

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-12">
      {/* HEADER WITH DONUT METRIC */}
      <div className="glass-card p-5 sm:p-7 rounded-2xl flex flex-col sm:flex-row items-center justify-between gap-5">
        <div className="space-y-1.5 text-center sm:text-left">
          <h1 className="font-serif text-xl sm:text-2xl font-bold text-[#1B1C1A] flex items-center justify-center sm:justify-start gap-2.5">
            <ShieldAlert size={22} className="text-[#C25E3E]" />
            Risk Early Warning Center
          </h1>
          <p className="text-xs text-[#8D8574]">
            Automated anomaly triggers generated by XGBoost & statutory CUF boundary heuristics
          </p>
        </div>

        {/* Mini Donut Chart */}
        <div className="flex items-center gap-4 bg-[#FAF9F5]/80 px-4 py-2 rounded-2xl border border-[rgba(61,58,52,0.08)]">
          <div className="w-20 h-20 sm:w-24 sm:h-24 shrink-0">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={donutData} innerRadius={22} outerRadius={36} dataKey="value" stroke="none">
                  {donutData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: 'rgba(255, 255, 255, 0.9)', 
                    backdropFilter: 'blur(10px)',
                    borderColor: 'rgba(61, 58, 52, 0.12)', 
                    borderRadius: '10px', 
                    fontSize: '11px',
                    fontFamily: 'Plus Jakarta Sans'
                  }} 
                />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div className="text-[11px] sm:text-xs font-mono space-y-1 tabular-nums">
            <div className="text-[#C25E3E] font-bold flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-[#C25E3E]" />
              {alertsData.critical_count} Critical
            </div>
            <div className="text-[#D97706] font-bold flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-[#D97706]" />
              {alertsData.high_count} High
            </div>
            <div className="text-[#2C3E50] font-bold flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-[#2C3E50]" />
              {alertsData.medium_count} Medium
            </div>
          </div>
        </div>
      </div>

      {/* FILTER & ACTIONS BAR */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        {/* Severity Toggles */}
        <div className="flex rounded-full bg-[#EFECE6] border border-[rgba(61,58,52,0.1)] p-1">
          {['All', 'CRITICAL', 'HIGH', 'MEDIUM'].map(s => (
            <button
              key={s}
              onClick={() => setSeverityFilter(s)}
              className={`px-3 py-1 text-[11px] sm:text-xs font-mono rounded-full transition-all ${
                severityFilter === s ? 'bg-[#1E1E1E] text-[#FAF9F5] font-bold shadow-xs' : 'text-[#655E4E] hover:text-[#1B1C1A]'
              }`}
            >
              {s}
            </button>
          ))}
        </div>

        <button
          onClick={handleResolveAll}
          className="btn-sovereign-secondary px-4 py-1.5 text-xs font-semibold flex items-center gap-1.5 hover:bg-[#4A5D4E] hover:text-white hover:border-[#4A5D4E] transition-all"
        >
          <CheckCheck size={14} />
          <span>Acknowledge All</span>
        </button>
      </div>

      {/* ALERTS FEED WITH ANIMATE PRESENCE */}
      <div className="space-y-3">
        <AnimatePresence>
          {(alertsData.alerts || []).map(alert => (
            <motion.div 
              key={alert.alert_id} 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.96 }}
              transition={{ duration: 0.25 }}
              className={`glass-card p-4 sm:p-5 rounded-2xl flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                alert.severity === 'CRITICAL' ? 'border-l-4 border-l-[#C25E3E] border-[rgba(194,94,62,0.22)]' :
                alert.severity === 'HIGH' ? 'border-l-4 border-l-[#D97706] border-[rgba(217,119,6,0.22)]' :
                'border-l-4 border-l-[#2C3E50] border-[rgba(44,62,80,0.22)]'
              }`}
            >
              <div className="space-y-1.5 flex-1 min-w-0">
                <div className="flex flex-wrap items-center gap-2">
                  <span className={`text-[9px] font-mono font-bold px-2 py-0.5 rounded-full uppercase ${
                    alert.severity === 'CRITICAL' ? 'badge-sienna' :
                    alert.severity === 'HIGH' ? 'badge-amber' :
                    'badge-indigo'
                  }`}>
                    {alert.severity}
                  </span>
                  <span className="text-xs font-bold text-[#1B1C1A]">{alert.alert_type}</span>
                  <span className="text-[10px] text-[#8D8574] font-mono">[{alert.project_id}]</span>
                </div>
                <h3 className="text-xs sm:text-sm font-semibold text-[#1B1C1A] line-clamp-1">{alert.project_name}</h3>
                <p className="text-xs text-[#655E4E] leading-relaxed">{alert.message}</p>
                <div className="flex items-center gap-3 text-[10px] font-mono text-[#8D8574] pt-0.5">
                  <span className="truncate max-w-[160px]">Sector: {alert.sector}</span>
                  <span>State: {alert.state}</span>
                </div>
              </div>

              <div className="flex items-center gap-2 shrink-0 self-start sm:self-auto">
                <Link
                  to={`/projects/${alert.project_id}`}
                  className="btn-sovereign-secondary px-3 py-1 text-xs font-semibold flex items-center gap-1.5"
                >
                  <span>Inspect</span>
                  <ExternalLink size={11} />
                </Link>
                <button
                  onClick={() => handleResolveOne(alert.alert_id)}
                  className="px-3 py-1 rounded-full border border-[rgba(61,58,52,0.14)] bg-[#FAF9F5] hover:bg-[#4A5D4E] hover:text-white hover:border-[#4A5D4E] text-[#655E4E] transition-all text-xs font-medium"
                >
                  Resolve
                </button>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>
    </div>
  );
}
