import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ShieldAlert, CheckCircle, ExternalLink, Filter, CheckCheck } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import { getAlerts, resolveAlert, resolveAllAlerts } from '../utils/api';

export default function Alerts() {
  const [alertsData, setAlertsData] = useState({ alerts: [], total_active: 0, critical_count: 0, high_count: 0, medium_count: 0, resolved_count: 0 });
  const [severityFilter, setSeverityFilter] = useState('All');
  const [loading, setLoading] = useState(true);

  async function loadAlerts() {
    try {
      setLoading(true);
      const res = await getAlerts({
        severity: severityFilter,
        limit: 100
      });
      setAlertsData(res);
    } catch (err) {
      console.error('Failed to load alerts:', err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadAlerts();
  }, [severityFilter]);

  const handleResolveOne = async (id) => {
    try {
      await resolveAlert(id);
      loadAlerts();
    } catch (err) {
      console.error(err);
    }
  };

  const handleResolveAll = async () => {
    try {
      await resolveAllAlerts();
      loadAlerts();
    } catch (err) {
      console.error(err);
    }
  };

  const donutData = [
    { name: 'Critical', value: alertsData.critical_count || 10, color: '#E11D48' },
    { name: 'High', value: alertsData.high_count || 30, color: '#D97706' },
    { name: 'Medium', value: alertsData.medium_count || 50, color: '#4F46E5' },
  ];

  return (
    <div className="max-w-7xl mx-auto space-y-4 sm:space-y-6 pb-12">
      {/* HEADER WITH DONUT METRIC */}
      <div className="intel-card p-4 sm:p-6 rounded-xl flex flex-col sm:flex-row items-center justify-between gap-4 bg-white">
        <div className="space-y-1 text-center sm:text-left">
          <h1 className="text-lg sm:text-xl font-bold text-[#0F172A] flex items-center justify-center sm:justify-start gap-2">
            <ShieldAlert size={20} className="text-rose-600" />
            Risk Early Warning Center
          </h1>
          <p className="text-xs text-[#64748B]">
            Automated anomaly triggers generated by XGBoost & CUF boundary rules
          </p>
        </div>

        {/* Mini Donut Chart */}
        <div className="flex items-center gap-3">
          <div className="w-20 h-20 sm:w-24 sm:h-24 shrink-0">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={donutData} innerRadius={22} outerRadius={36} dataKey="value" stroke="none">
                  {donutData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip contentStyle={{ backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: '8px', fontSize: '10px' }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div className="text-[11px] sm:text-xs font-mono space-y-0.5">
            <div className="text-rose-600 font-bold">{alertsData.critical_count} Critical</div>
            <div className="text-amber-600 font-bold">{alertsData.high_count} High</div>
            <div className="text-indigo-600 font-bold">{alertsData.medium_count} Medium</div>
          </div>
        </div>
      </div>

      {/* FILTER & ACTIONS BAR */}
      <div className="flex flex-wrap items-center justify-between gap-2.5">
        {/* Severity Toggles */}
        <div className="flex rounded-lg bg-white border border-[#CBD5E1] p-0.5 shadow-2xs">
          {['All', 'CRITICAL', 'HIGH', 'MEDIUM'].map(s => (
            <button
              key={s}
              onClick={() => setSeverityFilter(s)}
              className={`px-2.5 py-1 text-[11px] sm:text-xs font-mono rounded transition-colors ${
                severityFilter === s ? 'bg-indigo-600 text-white font-bold' : 'text-[#64748B]'
              }`}
            >
              {s}
            </button>
          ))}
        </div>

        <button
          onClick={handleResolveAll}
          className="px-3 py-1.5 rounded-lg bg-emerald-50 text-emerald-700 border border-emerald-200 hover:bg-emerald-600 hover:text-white transition-colors text-xs font-semibold flex items-center gap-1 shadow-2xs"
        >
          <CheckCheck size={13} />
          <span>Acknowledge All</span>
        </button>
      </div>

      {/* ALERTS FEED */}
      <div className="space-y-2.5">
        {(alertsData.alerts || []).map(alert => (
          <div 
            key={alert.alert_id} 
            className={`intel-card p-3.5 sm:p-4 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white ${
              alert.severity === 'CRITICAL' ? 'border-l-4 border-l-rose-500' :
              alert.severity === 'HIGH' ? 'border-l-4 border-l-amber-500' :
              'border-l-4 border-l-indigo-500'
            }`}
          >
            <div className="space-y-1 flex-1 min-w-0">
              <div className="flex flex-wrap items-center gap-1.5">
                <span className={`text-[9px] font-mono font-bold px-1.5 py-0.5 rounded uppercase ${
                  alert.severity === 'CRITICAL' ? 'bg-rose-100 text-rose-800' :
                  alert.severity === 'HIGH' ? 'bg-amber-100 text-amber-800' :
                  'bg-indigo-100 text-indigo-800'
                }`}>
                  {alert.severity}
                </span>
                <span className="text-xs font-bold text-slate-900">{alert.alert_type}</span>
                <span className="text-[10px] text-[#64748B] font-mono">[{alert.project_id}]</span>
              </div>
              <h3 className="text-xs sm:text-sm font-semibold text-slate-900 line-clamp-1">{alert.project_name}</h3>
              <p className="text-xs text-[#475569]">{alert.message}</p>
              <div className="flex items-center gap-3 text-[10px] font-mono text-[#64748B] pt-0.5">
                <span className="truncate max-w-[150px]">Sector: {alert.sector}</span>
                <span>State: {alert.state}</span>
              </div>
            </div>

            <div className="flex items-center gap-2 shrink-0 self-start sm:self-auto">
              <Link
                to={`/projects/${alert.project_id}`}
                className="px-2.5 py-1 rounded bg-indigo-50 text-indigo-700 border border-indigo-200 hover:bg-indigo-600 hover:text-white transition-colors text-xs font-semibold flex items-center gap-1"
              >
                <span>Inspect</span>
                <ExternalLink size={11} />
              </Link>
              <button
                onClick={() => handleResolveOne(alert.alert_id)}
                className="px-2.5 py-1 rounded bg-slate-100 hover:bg-emerald-600 hover:text-white text-slate-700 transition-colors text-xs font-medium"
              >
                Resolve
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
